# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Team Schwessinger"
title:              "Plants, Fungi, Evolution"
description:        "This is the webpage page for the Schwessinger Lab, we specialise in Rust and MinION and are situated at the Research School of Biology at the Australian  National University, Canberra, Australia."


# URL
url:               http://teamschwessinger.com/Team_B_S
baseurl:            
#baseurl:            "/Team_B_S" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "ABOUT"
    href:           "/about"
  - name:           "HOW TO JOIN"
    href:           "/how_to_join"  
  - name:           "PUBLICATIONS"
    href:           "/publication"
  - name:           "PEOPLE"
    href:           "/people"
  - name:           "RESOURCES"
    href:           "/resources"
  - name:           "OPEN SCIENCE"
    href:           "/open_science"
  - name:           "EXTRA"
    href:           "/extra"


# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
